import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
// TODO: Check how to manage translates
export const metadata: Metadata = {
  title: 'Дошка оголошень ' + process.env.domain + ': оголошення купівлі та продажу товарів України',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
