import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';
import Header from './_components/header';
import Footer from './_components/footer';

const inter = Inter({ subsets: ['latin'] })
// TODO: Check how to manage translations   title: 'Дошка оголошень ' + process.env.domain + ': оголошення купівлі та продажу товарів України',
export const metadata: Metadata = {
  title: 'development',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' min-h-screen'}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
